% Compute CR pre-bounds on mesh_regular_tet/level6 generated by Gmsh.

diary('cr_level6_from_file_log.txt'); diary on;

vfem_root = '/home/xfliu/Workspace/New_Project_SchrodingerEVP/VFEM_LIB/VFEM3D';
addpath(vfem_root);
addpath(genpath(fullfile(vfem_root, 'VFEM_Lib')));
addpath('/home/xfliu/Workspace/Paper_Plum_LG/Code');

old_pwd = pwd;
cd(vfem_root);
my_intlab_mode_config;
cd(old_pwd);
global INTERVAL_MODE; INTERVAL_MODE = 0;

mesh6 = mesh_load_from_folder(fullfile(vfem_root, 'mesh_regular_tet', 'level6', filesep));
[lb_cr6, eig_cr6, info_cr6] = schrodinger_eig_cr(mesh6, @(x,y,z)0, 5, 'dirichlet', 1.0);

save('cr_level6_from_file.mat', 'lb_cr6', 'eig_cr6', 'info_cr6');
fprintf('rho_2 = %.12f\n', lb_cr6(2));
fprintf('rho_5 = %.12f\n', lb_cr6(5));

diary off;
exit(0);
